### PR TITLE
fixed package.json warnings

### PR DESCRIPTION
**Pull request by vishal5251**
source: package.json, package-lock.json
fixed npm install warnings.

### CODE REVIEW

**Comment by vishal5251** [comment]
closes #22 
my twitter handle is @VishalJ95917351

**Comment by vishal5251** [comment]
close #22

**Comment by SuzeShardlow** [comment]
Thanks, @vishal5251!  If you are a member of our Discord (https://discord.com/invite/ueQwKUh5Z3), please drop your handle here and we will give you the Hacktoberfest 2021 role :) and if you'd like a shout out on Twitter, drop your handle!

**Comment by vishal5251** [comment]
> Thanks, @vishal5251! If you are a member of our Discord (https://discord.com/invite/ueQwKUh5Z3), please drop your handle here and we will give you the Hacktoberfest 2021 role :) and if you'd like a shout out on Twitter, drop your handle!

You're most welcome, vishal5251 is my discord username and @VishalJ95917351 is my twitter one. Thanks!

**Pull request merged**
